- json/navigation-conf/au.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
- riff-raff.yaml
Also, the stack doesn't need to be in the prefix, in fact it's breaking mobile-preview which cannot find the navigation
> Fix sustainable business

- json/navigation-conf/international.json
- src/main/scala/com/gu/navigation/model/NavigationSection.scala
- src/test/scala/com/gu/navigation/NavigationProviderTest.scala
Lifestyle international front should point to Lifestyle uk.
By adding an edition override option it should be possible to configure this behaviour.
> MSS-515: Support edition override

- json/navigation-conf/au.json
This add's the new flagship podcast "[Full Story](https://www.theguardian.com/australia-news/series/full-story)" to the podcast navigation in the Australian edition of the app. 
It also removes some outdated subjects, and changes the order to be as following:
Full Story
Politics
Today in Focus
Football 
Audio Long Reads
Science
Books
Tech
The Story
> MSS-1229: Update AUS podcast navigation

- json/navigation-conf/au.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
Editorial want the `Support Us` to be lowercase not uppercase.
> Change "Support Us" to a lowercase "U"

- json/navigation-conf/au.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
We have changed the path to the Games front - so it no longer goes to games tag page
> MSS-1664: Updated navigation path to Games

- json/navigation-conf/us.json
Removes US election from the nav as it is not needed anymore, as requested by Editorial.
> Remove US election from nav

- json/navigation-conf/au.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
This PR removes `Euro 2020` from sport and football navigations and adds `Tokyo 2020` to the sport navigation for all editions.
> LIVE-2820 - Remove euro 2020 and add tokyo 2020 to sport

- json/navigation-conf/au.json
Adds environment prefix to all the environment sections in the AU nav, as they are tags not fronts
> Make sure path is correct for AU Environment links

- json/navigation-conf/au.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
Add Tokyo 2020 Paralympics to sport nav in all editions
> LIVE-2988: Add Tokyo 2020 Paralympics to sport nav in all editions

- json/navigation-conf/au.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
This PR removes paralympics from all editions' sport nav
Check the app after deploying
> LIVE-3032 - remove paralympics from sport nav

- json/navigation-conf/us.json
As per request from Editorials, we changed the "Green Light" series to "Fight to Vote" series on the menu for US edition. 
I made the same change to the `us.json` for CODE and checked if the menu was updated correctly, the caption was correct and the link went to the correct page.
The menu was updated accordingly.
Yes.
> LIVE-3636 Change "Green Light" series to "Fight to Vote" series

- json/navigation-conf/au.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
Adds Politics Weekly UK, America and Weekend to all navs as requested by editorial
> LIVE-3793: Add Politics Weekly UK, America and Weekend to all navs

- json/navigation-conf/us.json
Editorials requested to add "F1" tag page to the end of the drop down menu for US/sport.
> Add F1 to US/sports

- json/navigation-conf/au.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
Per editorial's request, we add the fronts `obituaries` to the navigation menu.
Uploaded the JSON to S3 for CODE and check the response from [navigation](https://mobile-origin.mobile-aws.code.dev-guardianapis.com/uk/navigation)
> Add obituaries fronts to the nav

- json/navigation-conf/europe.json
This adds the navigation configuration file for the new Europe edition. 
At the moment, this is an exact copy of the International conf. file as we do not have Europe-specific navigation yet. This should be revisited closer to launch date. 
We need this in order to get the Europe edition into [MAPI](https://github.com/guardian/mobile-apps-api/tree/add-europe-edition-in-mapi) 
TBC
`europe/navigation` should work in MAPI
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology …
> Add Europe navigation cross platform navigation conf. file

- json/navigation-conf/us.json
The US sports desk have asked for the Golf [page](https://www.theguardian.com/sport/golf) to be added to sports menu dropdown in the US edition of the app.
After updating the json file I manually uploaded it to the S3 bucket and redeployed mobile-fronts to CODE. After that the golf page can be seen in the menu dropdown of the US edition of the debug app:
Following the link takes you to the expected page:
> Add golf to US sports section

- json/navigation-conf/us.json
As per request from Editorial, we changed the "Fight to Vote" series to "Fight for Democracy" on the menu for US edition.
The same change was made to the us.json for CODE, and we checked that the menu was updated correctly, the caption was correct and the link went to the correct page.
The menu was updated accordingly.
| Navigation | Series |
| --- | --- |
| ![Simulator Screen Shot - iPhone 14 - 2023-05-10 at 11 19 13](https://github.com/guardian/cross-platform-navigation/assets/55602675/0e3b2f8c-6f18-4b3d-b69f-e2ca8b84578d) | ![Simulator Screen Shot - iPhone 14 - 2023-05-10 at 11 19 19](https://github.com/guardian/cross-platform-navigation/assets/55602675/9c0e8f76-15f6-46bb-a1c1-8037bb1e29de) |
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people- …
> Change "Fight to Vote" to "Fight for Democracy" on US nav

- build.sbt
- version.sbt
The sbt-sonatype plugin wants this: https://github.com/xerial/sbt-sonatype#buildsbt
> Fix sbt release: add required `publishTo` field

- build.sbt
- Removed out-of-date comments
- Updated release process to use recommended steps from docs
- Bumped `specs2` to get Scala 2.13 version
> Cross-compile Scala 2.13

- json/navigation-conf/europe.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
We have been asked by editorial to remove coronavirus from navigation.
Removes Coronavirus from UK and International editions (currently on prod) and Europe edition (currently not in prod).
The same change was made to the uk.json, international.json in CODE, and the menu was updated correctly.
| --- | --- |
| ![Simulator Screen Shot - iPhone 14 - 2023-07-18 at 18 13 11](https://github.com/guardian/cross-platform-navigation/assets/55602675/875f2925-2f87-4367-88f5-d60fc23d94d7) | ![Simulator Screen Shot - iPhone 14 - 2023-07-18 at 18 11 32](https://github.com/guardian/cross-platform-navigation/assets/55602675/7fdcf0ce-70a4-4fec-8af3-4eeca04d7e8d) |
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#scr …
> Remove coronavirus from UK, International and Europe editions

- json/navigation-conf/us.json
The editorials are going to launch a new editionalized `us/soccer` front.  They want the existing `Soccer` item under `Sport` on US nav to go to this new front.
This PR is to replace the link of `Soccer` menu to this `us/soccer` front.
This PR should not be merged until the new US soccer front has been launched (planned on 4-Aug).
The modified JSON file was uploaded to the `CODE` location of S3 bucket. 
The front has not been launched so we have checked the response from the CODE `navigation` endpoint only.
| --- | --- |
| <img src="https://github.com/guardian/cross-platform-navigation/assets/89925410/5cf58eae-66f1-416a-a092-915fef109ccc" width="300px" /> | <img src="https://github.com/guardian/cross-platform-navigation/assets/89925410/838c577d-1dee-4c88-adec-2d6325d1d20 …
> LIVE-5503 Add the new editionalized us/soccer front to US nav

- json/navigation-conf/us.json
Football tables and competitions aren't showing up on the US edition of the nav but these nav elements are added dynamically in MAPI. We should parse the new US soccer front as a section front. Currently it defaults to a tag list but by providing the mobile override value here to ensure it's parsed correctly.
I tested in conjunction with the [corresponding](https://github.com/guardian/mobile-apps-api/pull/2656) MAPI PR.
> Ensure football competitions show up under US soccer front

- .github/workflows/ci.yml
- build.sbt
- project/plugins.sbt
This extends a pre-existing CI workflow to include uploading artifacts to riff-raff. As a result I've also removed the sbt-riffraff-artifact plugin.
There is only 1 deployment type specified for this project, an [aws-s3](https://riffraff.gutools.co.uk/docs/magenta-lib/types#awss3) deployment type (on deploy, we simply upload the navigation json to an s3 bucket in the mobile account).
There is no CODE deployment setup for this project. To test I did the following:
- Validated the CI workflow was [successful](https://github.com/guardian/cross-platform-navigation/actions/runs/5974012196/job/16207363375)
- Confirmed in the deploy tools riff raff artifacts bucket that, for the successful workflow, a corresponding set of artifacts existed, including the navigation json. Note that the json …
> Migrate riff-raff upload to GitHub actions

- .github/workflows/ci.yml
This updates the test report step in the CI workflow. The test report step now outputs a pretty print of the tests.
Given the test step in the workflow runs [successfully](https://github.com/guardian/cross-platform-navigation/actions/runs/5976535835/job/16214599669) we can now see a pretty version of the test results:
> Update test report

- json/navigation-conf/uk.json
This PR removes chips with everything, small changes and brexit means from the podcast subnav menu on the UK edition following a request from Central Production.
Updated the json in the CODE folder in s3, reployed mobile-fronts, checked on the debug app. If you'd like to do this yourself I've added some testing instructions to the readme of this repo. 
| --- | --- | 
| <img src="https://github.com/guardian/cross-platform-navigation/assets/102960825/b96ca74f-5413-4756-93d1-15b39bad0863" width="300px" /> | <img src="https://github.com/guardian/cross-platform-navigation/assets/102960825/ff054f90-44ac-453d-aedd-e2b7f66ec79e" width="300px" /> |
> Remove chips with everything, brexit means and small changes from podcast subnav menu

- .github/workflows/release.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
- version.sbt
[`gha-scala-library-release-workflow`](https://github.com/guardian/gha-scala-library-release-workflow) gives us an automated way to publish releases of this library without needing individual Sonatype credentials for each developer!
The configuration changes are all described in [the docs for `gha-scala-library-release-workflow`](https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/configuration.md).
We've also granted access to the release credentials through https://github.com/guardian/github-secret-access/pull/34.
See also the list of Guardian projects that have adopted this workflow so far: https://github.com/guardian/gha-scala-library-release-workflow/issues/20
> Adopt GHA-Scala-Library-Release-Workflow

- json/navigation-conf/us.json
- riff-raff.yaml
As per request from Central Production, this PR adds the item **US election 2024** to the nav menu for US edition.  It links to the front **us-news/us-elections-2024**
> On apps on US edition could we arrange for [US elections 2024](https://www.theguardian.com/us-news/us-elections-2024) be added beneath US and above Politics (so in second position down). No need to remove Politics there.
In addition, the riffraff configuration has also been changed to avoid having the bucket name directly.  As recommended by DevX quite a while ago, the bucket name was provided via a SSM parameter name instead.
The navigation menu JSON was tested on CODE.  Screenshots have been captured.
|Menu|Go to|
|---|---|
|<img width="360px" src="https://github.com/guardian/cross-platform-navigation/assets/89925410/c85 …
> LIVE-6235 Add US election 2024 to nav menu in US edition

- json/navigation-conf/europe.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
This PR adds the *Live events* to the nav menu of the app on UK, Europe and International editions, as per editorial request.
|UK|Europe|International|
|---|---|---|
|<img width="320px" src="https://github.com/guardian/cross-platform-navigation/assets/89925410/0d609d56-c4ff-42ba-84bc-bf2c29d95410" />|<img width="320px" src="https://github.com/guardian/cross-platform-navigation/assets/89925410/79f6f57e-a543-43a9-a157-756ef4b1d01e" />|<img width="320px" src="https://github.com/guardian/cross-platform-navigation/assets/89925410/be5b0e16-2795-434a-97a5-d995635381ca" />
> LIVE-6231 Add live events to nav for UK, EU, International editions

- json/navigation-conf/us.json
As per editorial request, this PR adds the "Donal Trump trials" item to the navigation menu on US edition.
|Before|After|
|---|---|
|<img src="https://github.com/guardian/cross-platform-navigation/assets/89925410/21dcb5d6-d875-4f5e-ae61-cd6805f332e6" width="320px" />|<img src="https://github.com/guardian/cross-platform-navigation/assets/89925410/10867f06-2063-48fb-a4b2-973af7df4083" width="320px" />|
> LIVE-6444 Add Donald Trump trials to us nav

- json/navigation-conf/us.json
This changes the tag path for `Sustainable Business` from `uk/sustainable-business` to `sustainable-business/sustainable-business`
This is because the tag `uk/sustainable-business` doesn't exist and the navigation link returns an error
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour …
> Fix sustainable business tag

- json/navigation-conf/europe.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
As per editorial request, update the Obituaries path from 
https://www.theguardian.com/obituaries
to
https://www.theguardian.com/tone/obituaries
for UK, Europe and International
Tested on CODE and checked navigating to Obituaries in the editions link to the correct page (currently broken on PROD)
> Update obituaries link

- json/navigation-conf/au.json
- json/navigation-conf/europe.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
add "Euro 2024" to the Sport navigation across all editions
requirements
- should navigate to https://www.theguardian.com/football/euro-2024
- should go in first place on the nav
- to be merged on Wednesday 13 June 2024
**UK**
**US**
> Add Euro 2024 to Sport nav

- json/navigation-conf/au.json
- json/navigation-conf/europe.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
Replace Euro 2024 with Olympics 2024 in Sports nav
Link: https://www.theguardian.com/sport/olympic-games-2024
Copy: [Olympics 2024](https://www.theguardian.com/sport/olympic-games-2024)
| --- | --- |
| <img width="300px" src="https://github.com/user-attachments/assets/610b6c7a-94ee-44d8-96b1-1ffe88560537" /> |<img width="300px" src="https://github.com/user-attachments/assets/15383cac-5559-4727-9bbe-9df7d0785f84" /> |
> Remove Euros and add Olympics to the nav

- json/navigation-conf/us.json
Add Olympics 2024 to US main nav and remove Donald Trump trials
| -- | -- |
| <img src="https://github.com/user-attachments/assets/8ecd8aa1-4dcf-4cf6-a7e7-0b85536af213" width="300px" /> | <img src="https://github.com/user-attachments/assets/dc901c08-eaad-4f5d-8713-3da29b908843" width="300px" /> |
> Add Olympics 2024 to US main nav

- json/navigation-conf/us.json
CP request
- remove Olympics 2024 from the main nav list 
- add a link for Democratic national convention in third slot, after US elections https://www.theguardian.com/us-news/democratic-national-convention-2024
- Under Sports, remove Olympics 2024 
To add Paralympics on or around 28th August
> Remove olympics from US nav

- json/navigation-conf/au.json
- json/navigation-conf/europe.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
Remove olympics from nav for all the remaining editions
> Remove Olympics from nav

- json/navigation-conf/au.json
- json/navigation-conf/europe.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
Add Paralympics to all editions nav (to be merged close to 26 August)
- In the main and under sports nav for US
- Under Sports in all other regions
**UK**
**US**
**Aus**
**Europe**
**International**
> Add Paralympics 2024

- json/navigation-conf/us.json
As per editorials' request, this pull request removes the menu item "Democratic national convention" from the US navigation menu. 
The updated menu was tested on CODE.
| --- | --- |
| <img width="300px" src="https://github.com/user-attachments/assets/8d0b3a15-0198-4ae1-8c23-0261d48706fe" /> | <img width="300px" src="https://github.com/user-attachments/assets/e08ff547-eac1-4862-8883-c9e950cedbcb" />
> Remove democratic national convention from US nav

- build.sbt
- src/main/scala/com/gu/navigation/model/NavigationSection.scala
This is prompted by https://github.com/guardian/mobile-apps-api/issues/3198 - we would like to be able to upgrade MAPI to Scala 3. As MAPI depends on https://github.com/guardian/cross-platform-navigation, it's good to have a Scala 3 version of this library.
The only tricky part of upgrading `cross-platform-navigation` to Scala 3 is handling the explicit call to the `unapply()` method, which _used_ to return an `Option[(...,...,...)]` with all the parameters used to create the case class - in Scala 3 that's changed:
* https://docs.scala-lang.org/scala3/guides/migration/incompat-other-changes.html#explicit-call-to-unapply
* https://github.com/scala/scala3/issues/2335
The least magical way to cope with the changed `unapply()` method is to manually write out what the unapply method used to …
> Support Scala 3

- json/navigation-conf/au.json
As per editorials request, this pull request adds a new item named "Health" pointing to the Australia health news front (`australia-news/health`) to AU nav between "Environment" and "Science".
The change was validated on `CODE`.
| --- | --- |
| <img width="360px" src="https://github.com/user-attachments/assets/90df213d-9fa9-47d6-b865-d6c463efdf68" /> | <img width="360px" src="https://github.com/user-attachments/assets/0fe22505-29ed-4720-b7ca-2cd41a9490d5" /> |
This "Health" item takes us here:
> Add Australia health news to AU nav

- json/navigation-conf/uk.json
Add The Filter to the UK sub-nav which should navigate to the `/uk/thefilter` front.
The content/front is not published yet so I've tested by setting up a CODE front with `uk/thefilter`.
Once this front goes live, I'll test again before merging.
| iOS | Android |
| -- | -- |
> Add The Filter to UK sub-nav

- json/navigation-conf/au.json
- json/navigation-conf/europe.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
- json/navigation-conf/us.json
CP requested
- change "Support us" to this link on all editions to https://www.theguardian.com/insidetheguardian for all editions
- add WNBA below NBA for US
Tested on CODE
| Support Us | WNBA (US) |
|------------|-----------|
| <img src="https://github.com/user-attachments/assets/1cec3e9c-6473-4f19-82f0-56db38a390cc" width="200px" /> | <img src="https://github.com/user-attachments/assets/3abb9dd3-aaae-485a-bcbf-b9af31e68ae2" width="200px" /> |
> add WNBA (US) and update support us link (all editions)

- README.md
- riff-raff.yaml
Until now we have been testing nav changes manually by uploading the files into the S3 `/CODE` folder directly on the AWS console without using RiffRaff. But I have tested that we can actually use RiffRaff to deploy to the CODE bucket. 
I suspect this has always been possible because [RiffRaff pre-fixes the target stage to the bucket key](https://github.com/guardian/riff-raff/blob/30e98413b89bf29692ccf1af6f003f53f5fb093b/magenta-lib/src/main/scala/magenta/deployment_type/S3.scala#L92-L93) but it seems we were (unintentionally and unfortunately) misled by the outdated deployment restriction message on riffraff.
The following are more of cosmetic changes.
Changes:
- set `allowedStages` to CODE and PROD to constrain available stages on RiffRaff
- set `prefixStage` to true (default value but …
> Enable riffraff deployment to CODE

- json/navigation-conf/europe.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
As per editorial request, this pull request adds the nav item `US elections 2024` to the nav menu of UK, Europe and International editions.
The updated menu was validated on `CODE`.  Screenshots are pasted below:
| UK | Europe | International |
| --- | --- | --- |
| <img width="240px" src="https://github.com/user-attachments/assets/828a3aa5-cf2b-4513-a359-54d3bfacf989" /> | <img width="240px" src="https://github.com/user-attachments/assets/07ad011d-790e-4d19-a227-a0ebdf37473b" /> | <img width="240px" src="https://github.com/user-attachments/assets/b7df156e-f2d8-4aa7-a025-8b3d49f9fc28" /> |
The nav item takes users to the front on US elections 2024:
> Add US elections 2024

- json/navigation-conf/us.json
The duplicate US politics id was crashing the android app so removing it.
As a next step we should add a test to check there are no duplicate entries to catch cases like this.
Do not merge until Android devs are done with testing a related change on their end
Deployed to code and tested with android emulator.
Navigating to Politics in US edition no longer crashes.
> remove duplicate us politics from us nav (DO NOT MERGE)

- json/navigation-conf/us.json
This adds the Climate Crisis to the us navigation under Environment as requested by CP
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Add climate crisis to us nav

- json/navigation-conf/europe.json
- json/navigation-conf/international.json
- json/navigation-conf/uk.json
Removes The Observer
To be released Apr 22
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Remove Observer links
