guardian/cross-platform-navigation

json/navigation-conf/au.json, json/navigation-conf/international.json, json/navigation-conf/uk.json, json/navigation-conf/us.json
=> Mss 360/moving food

json/navigation-conf/uk.json
=> add section

json/navigation-conf/uk.json, json/navigation-conf/us.json
- Update the UK navigation to include `Election 2019`
- Update the US navigation to include `Election 2020`
=> MSS-1265: Update navigation for Elections

json/navigation-conf/au.json, json/navigation-conf/international.json, json/navigation-conf/uk.json, json/navigation-conf/us.json
Does what it says on the tin ⬆️
=> Remove cities from navigation

json/navigation-conf/international.json, json/navigation-conf/uk.json
Underneath UK on UK and International
=> add coronavirus to UK and International

json/navigation-conf/au.json, json/navigation-conf/international.json, json/navigation-conf/uk.json, json/navigation-conf/us.json
Change membership to support us in the navigation
=> Change membership to support us

json/navigation-conf/international.json, json/navigation-conf/uk.json
Add Euro 2020 to football and sports navs for UK and International
=> Add Euro 2020 to football and sports navs for UK and International

json/navigation-conf/us.json
Adds the green light series to US nav
=> LIVE-2823: Add green light series to US nav

json/navigation-conf/us.json
Adds the green light series to the environment section in US nav
=> Add green light series to environment section in US nav

json/navigation-conf/au.json
Removes global development from AU environment section, and adds more environment related links.
=> Refactor AU Environment navigation section

json/navigation-conf/au.json, json/navigation-conf/international.json, json/navigation-conf/uk.json, json/navigation-conf/us.json
Change path for paralympic games to be "sport/tokyo-paralympic-games-2020"
=> LIVE-2988: Change path for paralympic games to be "sport/tokyo-paralympic-games-2020"

json/navigation-conf/au.json, json/navigation-conf/international.json, json/navigation-conf/uk.json, json/navigation-conf/us.json
Adds winter olympics to all editions under the sport section, as requested by editorial
=> Add winter olympics to all editions under the sport section

json/navigation-conf/au.json, json/navigation-conf/international.json, json/navigation-conf/uk.json, json/navigation-conf/us.json
Removes winter olympics from all editions navs as requested by editorial
=> Remove winter olympics from all editions navs

json/navigation-conf/international.json, json/navigation-conf/uk.json
CP would like the women's euros added as a subnav link to the football section, uk and international editions only
=> Add women's euros to football

build.sbt
Bumps play json and jackson databind to fix high vulnerability alerts.
Compile and test both successful
=> bump play json and jackson-databind to fix high vulnerability alerts

README.md
To show which Scala versions this package is published against.
=> Add Scaladex Badge

project/build.properties, project/plugins.sbt
Reverts guardian/cross-platform-navigation#52
Sbt needs some more changes, see #53
=> Revert "Updated sbt To 1.9.0"

.github/workflows/ci.yml, .gitignore, build.sbt, project/build.properties, project/plugins.sbt, version.sbt
- Added configuration to surface CI test results in GH UI
- Upgraded sbt plugins
- Specified Java 11
=> Upgraded To sbt 1.9.0

build.sbt, project/plugins.sbt
Taken from #51, but reverting Scala 2.13 upgrade. We actually want to set up cross-compilation instead.
=> Dependency Updates

json/navigation-conf/au.json, json/navigation-conf/us.json
Further to #75, update the obituaries path to tone/obituaries for Aus and US
**Aus**
|Before|After|
|---|---|
**US**
|Before|After|
|---|---|
|<img src="https://github.com/guardian/cross-platform-navigation/assets/47318984/8641a563-fc29-48ec-826f-d6f694a2c9d3" width="300px" /> |<img src="https://github.com/guardian/cross-platform-navigation/assets/47318984/c18fc5b7-075c-4742-9d8c-c92735667578" width="300px" />
=> Update obituaries path for US and Aus

json/navigation-conf/au.json, json/navigation-conf/europe.json, json/navigation-conf/international.json, json/navigation-conf/uk.json, json/navigation-conf/us.json
Remove Paralympics from the nav bar
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
=> Remove paralympics

.github/workflows/ci.yml
Adds scala setup https://github.com/guardian/setup-scala to github actions
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
=> Use setup-scala

json/navigation-conf/us.json
Add the Filter US in navigation-v1 menu
Tested in https://github.com/guardian/mobile-apps-api/pull/3922
=> Add the Filter US to US nav
